/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import dow.ConnectionProvider;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class dentalAdminPanel2 extends javax.swing.JFrame {

    private int employeeIDD = 0;
    /**
     * Creates new form dentalAdminPanel2
     */
    public dentalAdminPanel2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private boolean validateFields(String formType) {
        if (formType.equals("edit") && !employeeName.getText().equals("") && !employeeID.getText().equals("") && !employeePassword.getText().equals("") && !employeeRePassword.getText().equals("")) {
            return false;
        } else if (formType.equals("new") && !employeeName.getText().equals("") && !employeeID.getText().equals("") && !employeePassword.getText().equals("") && !employeeRePassword.getText().equals("")) {
            return false;
        } else {
            return true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        employeeID = new javax.swing.JTextField();
        employeeName = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        employeeRePassword = new javax.swing.JPasswordField();
        employeePassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);
        saveBtn.setBounds(960, 610, 120, 40);

        removeBtn.setBorderPainted(false);
        removeBtn.setContentAreaFilled(false);
        removeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(removeBtn);
        removeBtn.setBounds(790, 610, 120, 40);

        editBtn.setBorderPainted(false);
        editBtn.setContentAreaFilled(false);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn);
        editBtn.setBounds(960, 540, 120, 40);

        addBtn.setBorderPainted(false);
        addBtn.setContentAreaFilled(false);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(790, 540, 120, 40);

        employeeID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeID.setBorder(null);
        jPanel1.add(employeeID);
        employeeID.setBounds(840, 260, 250, 30);

        employeeName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeName.setBorder(null);
        jPanel1.add(employeeName);
        employeeName.setBounds(840, 160, 250, 30);

        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(1060, 40, 50, 60);

        employeeRePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeRePassword.setBorder(null);
        jPanel1.add(employeeRePassword);
        employeeRePassword.setBounds(840, 450, 250, 30);

        employeePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeePassword.setBorder(null);
        jPanel1.add(employeePassword);
        employeePassword.setBounds(840, 350, 250, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee ID", "Employee Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 630, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maggie\\Desktop\\ClearView Images\\adminPanel.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentShown(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 710);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", null, JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            this.setVisible(false);
            new employeeLoginFrame().setVisible(true);
        }
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    if (validateFields("new")){
        JOptionPane.showMessageDialog(null, "Fields cannott be left blank.",null, JOptionPane.ERROR_MESSAGE);
        return;
        
    }
  
        String name = employeeName.getText();
        String ID = employeeID.getText();
        String password = employeePassword.getText();
        String repassword = employeeRePassword.getText();
        
      
        try (Connection con = ConnectionProvider.getCon()) {
            String sql = "INSERT INTO employeeaccounts (employeeName, employeeUserName, employeePassword) VALUES (?,?, ?)";
            try (PreparedStatement ps = con.prepareStatement(sql)) {
                
                ps.setString(0, ID);
                ps.setString(1, name);
                ps.setString(2, password);
                 
                
                if(!password.contains(repassword)){
                    JOptionPane.showMessageDialog(null, "Passwords does not match");
                    
                }
                else{
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "User added successfully.");
                setVisible(false);
                new dentalAdminPanel2().setVisible(true);
                }
            }
        }catch (SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(null,"User ID already exist.");
            employeeName.setText("");
            employeeID.setText("");
            employeePassword.setText("");
            employeeRePassword.setText("");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error saving user.", "Error", JOptionPane.ERROR_MESSAGE);
            employeeName.setText("");
            employeeID.setText("");
            employeePassword.setText("");
            employeeRePassword.setText("");
            
            
        }
        formComponentShown(null);
        
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void jLabel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT *FROM employeeaccounts");
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("employeeID"),rs.getString("employeeName"),rs.getString("employeePassword")});
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        editBtn.setEnabled(false);
        
        
    }//GEN-LAST:event_formComponentShown

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
if (validateFields("new")){
        JOptionPane.showMessageDialog(null, "Fields cannott be left blank.",null, JOptionPane.ERROR_MESSAGE);
        return;
        
        }
        String name = employeeName.getText();
        String ID = employeeID.getText();
@SuppressWarnings("deprecation")
        String password = employeePassword.getText();
@SuppressWarnings("deprecation")
        String repassword = employeeRePassword.getText();
        
        int selectedRow = jTable1.getSelectedRow();
        
        
    if (selectedRow != -1) {
        // Update the table model with new values
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(ID, selectedRow, 0); // Update Employee ID
        model.setValueAt(name, selectedRow, 1); // Update Employee Name
        model.setValueAt(password, selectedRow, 2); // Update Password

        // Update in the database
        Connection con = null;
        PreparedStatement ps = null;

        try {
            con = ConnectionProvider.getCon();
            String sql = "UPDATE employeeaccounts SET employeeID=?, employeeName=?, employeePassword=? WHERE ID=?";
            ps = con.prepareStatement(sql);

                ps.setString(1, ID);
                ps.setString(2, name);
                ps.setString(3, password);
                ps.setInt(4, employeeIDD);
            

            // Execute update
            int rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "User Updated Successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "User not found or no change in data.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error updating user.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (ps != null) ps.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a row to update.", "Error", JOptionPane.ERROR_MESSAGE);
    }

        
        Connection con = null;
        PreparedStatement ps = null;
            
            try {
            con = ConnectionProvider.getCon();
            String sql = "UPDATE employeeaccounts SET employeeID=?, employeeName=?, employeePassword=? WHERE ID=?";
            ps = con.prepareStatement(sql);

            ps.setString(0, ID);
            ps.setString(1, name);
            ps.setString(2, password);

            // Execute update
            int rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "User Updated Successfully!");
                setVisible(false);
                new dentalAdminPanel2().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "User not found or no change in data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        
            
        }catch (SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(null,"User ID already exist.");
            employeeName.setText("");
            employeeID.setText("");
            employeePassword.setText("");
            employeeRePassword.setText("");
        }catch(SQLException e){
            e.printStackTrace();
            employeeName.setText("");
            employeeID.setText("");
            employeePassword.setText("");
            employeeRePassword.setText("");
            
        }
        formComponentShown(null);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int selectedRow = jTable1.getSelectedRow();

            // Get values from the selected row based on column index
            String employeeIDValue = jTable1.getValueAt(selectedRow, 0).toString();
            String employeeNameValue = jTable1.getValueAt(selectedRow, 1).toString();
            String employeePasswordValue = jTable1.getValueAt(selectedRow, 2).toString();

            // Set the values in the respective text fields
            employeeID.setText(employeeIDValue);
            employeeName.setText(employeeNameValue);
            employeePassword.setText(employeePasswordValue);
            
            employeeID.setEnabled(false);
            employeeName.setEnabled(false);
            employeePassword.setEnabled(false);
            employeeRePassword.setEnabled(false);
            
            editBtn.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        employeeID.setEnabled(true);
            employeeName.setEnabled(true);
            employeePassword.setEnabled(true);
            employeeRePassword.setEnabled(true);
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dentalAdminPanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dentalAdminPanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dentalAdminPanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dentalAdminPanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dentalAdminPanel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField employeeID;
    private javax.swing.JTextField employeeName;
    private javax.swing.JPasswordField employeePassword;
    private javax.swing.JPasswordField employeeRePassword;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
