/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic;

import java.awt.Color;

/**
 *
 * @author Maggie
 */
public class dentalHomePage extends javax.swing.JFrame {

    /**
     * Creates new form dentalHomePage
     */
    public dentalHomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        recordsBtn = new javax.swing.JButton();
        QueueBtn = new javax.swing.JButton();
        editQueueBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1);
        jButton1.setBounds(1060, 40, 70, 50);

        homeBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(460, 0, 100, 130);

        recordsBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        recordsBtn.setText("Patient Records");
        recordsBtn.setBorderPainted(false);
        recordsBtn.setContentAreaFilled(false);
        recordsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recordsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recordsBtnMouseExited(evt);
            }
        });
        jPanel1.add(recordsBtn);
        recordsBtn.setBounds(580, 0, 170, 130);

        QueueBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        QueueBtn.setText("Queue");
        QueueBtn.setBorderPainted(false);
        QueueBtn.setContentAreaFilled(false);
        QueueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QueueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QueueBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QueueBtnMouseExited(evt);
            }
        });
        jPanel1.add(QueueBtn);
        QueueBtn.setBounds(730, 0, 170, 130);

        editQueueBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editQueueBtn.setText("Edit Queue");
        editQueueBtn.setBorderPainted(false);
        editQueueBtn.setContentAreaFilled(false);
        editQueueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editQueueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editQueueBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editQueueBtnMouseExited(evt);
            }
        });
        jPanel1.add(editQueueBtn);
        editQueueBtn.setBounds(860, 0, 170, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maggie\\Desktop\\ClearView Images\\Homepage.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 710);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setForeground(Color.decode("#4b64b7"));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setForeground(Color.decode("#000000"));
    }//GEN-LAST:event_homeBtnMouseExited

    private void recordsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordsBtnMouseEntered
        recordsBtn.setForeground(Color.decode("#4b64b7"));
    }//GEN-LAST:event_recordsBtnMouseEntered

    private void recordsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordsBtnMouseExited
        recordsBtn.setForeground(Color.decode("#000000"));
    }//GEN-LAST:event_recordsBtnMouseExited

    private void QueueBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueueBtnMouseEntered
        QueueBtn.setForeground(Color.decode("#4b64b7"));
    }//GEN-LAST:event_QueueBtnMouseEntered

    private void QueueBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueueBtnMouseExited
        QueueBtn.setForeground(Color.decode("#000000"));
    }//GEN-LAST:event_QueueBtnMouseExited

    private void editQueueBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editQueueBtnMouseEntered
        editQueueBtn.setForeground(Color.decode("#4b64b7"));
    }//GEN-LAST:event_editQueueBtnMouseEntered

    private void editQueueBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editQueueBtnMouseExited
        editQueueBtn.setForeground(Color.decode("#000000"));
    }//GEN-LAST:event_editQueueBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dentalHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dentalHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dentalHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dentalHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dentalHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QueueBtn;
    private javax.swing.JButton editQueueBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton recordsBtn;
    // End of variables declaration//GEN-END:variables
}
