package dental_clinic;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//hi
/**
 *
 * @author Ana Marie Lim
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import dow.ConnectionProvider;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import static dental_clinic.patientRecordTable.patientVariable;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
public class fullPatientRecord extends javax.swing.JFrame {

    /** Creates new form fullPatientRecord */
    public fullPatientRecord() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        fname.setBorder(null);
        dateOfBirth.setBorder(null);
        contactNumber.setBorder(null);
        emergencyContact.setBorder(null);
        allergiesField.setBorder(null);
        addressField.setBorder(null);
        maleBtn.setBorder(null);        
        femaleBtn.setBorder(null);        
        
        fname.setEditable(false);
        dateOfBirth.setEditable(false);
        contactNumber.setEditable(false);
        emergencyContact.setEditable(false);
        allergiesField.setEditable(false);
        addressField.setEditable(false);
        maleBtn.setEnabled(false);
        femaleBtn.setEnabled(false);
        
        
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rsCheck = st.executeQuery("SELECT * FROM patientinfo WHERE patientName ='" + patientVariable + "'");
            
            if(rsCheck.next()){
                String pGender = rsCheck.getString("patientGender");
                
                if(pGender.equals("Male")){
                    maleBtn.setSelected(true);
                }else{
                    femaleBtn.setSelected(true);
                }
                
                
                fname.setText(rsCheck.getString("patientName"));
                dateOfBirth.setText(rsCheck.getString("patientBod"));
                contactNumber.setText(rsCheck.getString("patientContact"));
                emergencyContact.setText(rsCheck.getString("patientEmergency"));
                allergiesField.setText(rsCheck.getString("patientAllergies"));
                addressField.setText(rsCheck.getString("patientAddress"));
                
                
                
            }
            
            
        }
        catch(Exception e){
            
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        emergencyContact = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        allergiesField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 710));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(1170, 710));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 710));
        jPanel1.setLayout(null);

        updateButton.setBorderPainted(false);
        updateButton.setContentAreaFilled(false);
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton);
        updateButton.setBounds(798, 65, 130, 42);

        editButton.setBorderPainted(false);
        editButton.setContentAreaFilled(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton);
        editButton.setBounds(946, 65, 135, 42);

        backButton.setContentAreaFilled(false);
        jPanel1.add(backButton);
        backButton.setBounds(70, 643, 40, 30);

        buttonGroup2.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maleBtn.setText("Male");
        maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(maleBtn);
        maleBtn.setBounds(690, 340, 70, 60);

        buttonGroup2.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        femaleBtn.setText("Female");
        jPanel1.add(femaleBtn);
        femaleBtn.setBounds(810, 340, 100, 60);

        emergencyContact.setToolTipText("");
        jPanel1.add(emergencyContact);
        emergencyContact.setBounds(190, 520, 370, 20);

        contactNumber.setToolTipText("");
        jPanel1.add(contactNumber);
        contactNumber.setBounds(190, 422, 370, 30);

        dateOfBirth.setToolTipText("");
        jPanel1.add(dateOfBirth);
        dateOfBirth.setBounds(190, 330, 370, 30);

        fname.setToolTipText("");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(190, 232, 370, 30);

        allergiesField.setToolTipText("");
        jPanel1.add(allergiesField);
        allergiesField.setBounds(690, 242, 380, 20);

        addressField.setToolTipText("");
        jPanel1.add(addressField);
        addressField.setBounds(690, 472, 380, 30);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ana Marie Lim\\Documents\\Dental\\2\\Updated\\Update Full Patient Record.png")); // NOI18N
        background.setText("asd");
        background.setMaximumSize(new java.awt.Dimension(1170, 710));
        background.setMinimumSize(new java.awt.Dimension(1170, 710));
        jPanel1.add(background);
        background.setBounds(0, 0, 1170, 708);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        fname.setEditable(true);
        dateOfBirth.setEditable(true);
        contactNumber.setEditable(true);
        emergencyContact.setEditable(true);
        allergiesField.setEditable(true);
        addressField.setEditable(true);
        maleBtn.setEnabled(true);
        femaleBtn.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        System.out.println("save button clicked");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fullPatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField allergiesField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emergencyContact;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JTextField fname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
