package dental_clinic;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ana Marie Lim
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import dow.ConnectionProvider;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import static dental_clinic.patientRecordTable.patientVariable;
import javax.swing.JOptionPane;
public class fullPatientRecord extends javax.swing.JFrame {

    /** Creates new form fullPatientRecord */
    public fullPatientRecord() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        fullnameField.setEditable(false);
        dobField.setEditable(false);
        contactField.setEditable(false);
        emergencycontactField.setEditable(false);
        allergiesField.setEditable(false);
        addressField.setEditable(false);
        maleBtn.setEnabled(false);
        femaleBtn.setEnabled(false);
        
        
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rsCheck = st.executeQuery("SELECT * FROM patientinfo WHERE patientName ='" + patientVariable + "'");
            
            if(rsCheck.next()){
                String pGender = rsCheck.getString("patientGender");
                
                if(pGender.equals("Male")){
                    maleBtn.setSelected(true);
                }else{
                    femaleBtn.setSelected(true);
                }
                
                
                fullnameField.setText(rsCheck.getString("patientName"));
                dobField.setText(rsCheck.getString("patientBod"));
                contactField.setText(rsCheck.getString("patientContact"));
                emergencycontactField.setText(rsCheck.getString("patientEmergency"));
                allergiesField.setText(rsCheck.getString("patientAllergies"));
                addressField.setText(rsCheck.getString("patientAddress"));
                
                
                
            }
            
            
        }
        catch(Exception e){
            
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        fullnameField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        emergencycontactField = new javax.swing.JTextField();
        allergiesField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 710));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(1170, 710));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 710));
        jPanel1.setLayout(null);

        editButton.setBorderPainted(false);
        editButton.setContentAreaFilled(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton);
        editButton.setBounds(642, 65, 138, 42);

        saveButton.setBorderPainted(false);
        saveButton.setContentAreaFilled(false);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton);
        saveButton.setBounds(798, 65, 136, 42);

        removeButton.setBorderPainted(false);
        removeButton.setContentAreaFilled(false);
        removeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton);
        removeButton.setBounds(946, 65, 135, 42);

        backButton.setContentAreaFilled(false);
        jPanel1.add(backButton);
        backButton.setBounds(70, 643, 40, 30);

        fullnameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fullnameField.setBorder(null);
        jPanel1.add(fullnameField);
        fullnameField.setBounds(180, 240, 370, 25);

        dobField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dobField.setBorder(null);
        jPanel1.add(dobField);
        dobField.setBounds(190, 325, 370, 30);

        contactField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactField.setBorder(null);
        jPanel1.add(contactField);
        contactField.setBounds(180, 415, 370, 30);

        emergencycontactField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emergencycontactField.setBorder(null);
        jPanel1.add(emergencycontactField);
        emergencycontactField.setBounds(190, 520, 360, 25);

        allergiesField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allergiesField.setBorder(null);
        jPanel1.add(allergiesField);
        allergiesField.setBounds(690, 235, 360, 30);

        addressField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressField.setBorder(null);
        jPanel1.add(addressField);
        addressField.setBounds(700, 470, 350, 30);

        buttonGroup1.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maleBtn.setText("Male");
        maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(maleBtn);
        maleBtn.setBounds(690, 340, 70, 60);

        buttonGroup1.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        femaleBtn.setText("Female");
        jPanel1.add(femaleBtn);
        femaleBtn.setBounds(810, 340, 100, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paul Laurence Reyes\\Documents\\NU\\2nd Year\\DATA STRUCTURES AND ALGORITHMS\\Dental_UI\\Homepage (3).png")); // NOI18N
        jLabel1.setText("asd");
        jLabel1.setMaximumSize(new java.awt.Dimension(1170, 710));
        jLabel1.setMinimumSize(new java.awt.Dimension(1170, 710));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 708);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        System.out.println("edit button clicked");
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        System.out.println("remove button clicked");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        System.out.println("save button clicked");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fullPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fullPatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField allergiesField;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField dobField;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emergencycontactField;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
