/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic;

import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;


public class patientInformationFrame extends javax.swing.JFrame {

    /**
     * Creates new form patientInformationFrame
     */
    public patientInformationFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connect();
    }
    
    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dental", "root", "helios5600");
            System.out.println("Connected!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(patientInformationFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error 1!");
        } catch (SQLException ex) {
            Logger.getLogger(patientInformationFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error 2!");
        }

    }

     
            Connection con;
            PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        patientName = new javax.swing.JTextField();
        patientBday = new javax.swing.JTextField();
        patientNumber = new javax.swing.JTextField();
        patientEmergencyCon = new javax.swing.JTextField();
        patientAddress = new javax.swing.JTextField();
        patientAllergies = new javax.swing.JTextField();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        pregnantBtn = new javax.swing.JRadioButton();
        seniorBtn = new javax.swing.JRadioButton();
        pwdBtn = new javax.swing.JRadioButton();
        naBtn = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        patientName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientName.setBorder(null);
        jPanel1.add(patientName);
        patientName.setBounds(180, 200, 370, 30);

        patientBday.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientBday.setBorder(null);
        patientBday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBdayActionPerformed(evt);
            }
        });
        jPanel1.add(patientBday);
        patientBday.setBounds(180, 295, 380, 25);

        patientNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientNumber.setBorder(null);
        patientNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNumberActionPerformed(evt);
            }
        });
        jPanel1.add(patientNumber);
        patientNumber.setBounds(180, 380, 380, 30);

        patientEmergencyCon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientEmergencyCon.setBorder(null);
        patientEmergencyCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientEmergencyConActionPerformed(evt);
            }
        });
        jPanel1.add(patientEmergencyCon);
        patientEmergencyCon.setBounds(180, 480, 370, 30);

        patientAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientAddress.setBorder(null);
        jPanel1.add(patientAddress);
        patientAddress.setBounds(190, 565, 360, 30);

        patientAllergies.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientAllergies.setBorder(null);
        jPanel1.add(patientAllergies);
        patientAllergies.setBounds(690, 200, 360, 30);

        maleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maleBtn.setText("Male");
        maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(maleBtn);
        maleBtn.setBounds(690, 300, 70, 60);

        femaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        femaleBtn.setText("Female");
        jPanel1.add(femaleBtn);
        femaleBtn.setBounds(810, 300, 100, 60);

        pregnantBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pregnantBtn.setText("Pregnant Woman");
        jPanel1.add(pregnantBtn);
        pregnantBtn.setBounds(670, 520, 250, 20);

        seniorBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seniorBtn.setText("Senior Citizen");
        jPanel1.add(seniorBtn);
        seniorBtn.setBounds(670, 460, 180, 20);

        pwdBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdBtn.setText("Person with Disability");
        pwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(pwdBtn);
        pwdBtn.setBounds(670, 490, 250, 20);

        naBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        naBtn.setText("N/A");
        naBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naBtnActionPerformed(evt);
            }
        });
        jPanel1.add(naBtn);
        naBtn.setBounds(670, 550, 250, 20);

        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(1060, 640, 50, 40);

        returnBtn.setBorderPainted(false);
        returnBtn.setContentAreaFilled(false);
        returnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnBtn);
        returnBtn.setBounds(60, 630, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maggie\\Desktop\\ClearView Images\\infoFrame.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 710);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientEmergencyConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientEmergencyConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientEmergencyConActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        String name = patientName.getText();
        String bday = patientBday.getText();
        String contact = patientNumber.getText();
        String emergency = patientEmergencyCon.getText();
        String address = patientAddress.getText();
        String allergies = patientAllergies.getText();


        buttonGroup1.add(maleBtn);
        buttonGroup1.add(femaleBtn);

        // Set action commands for gender buttons
        maleBtn.setActionCommand("Male");
        femaleBtn.setActionCommand("Female");

        // Group priority radio buttons
        buttonGroup2.add(pregnantBtn);
        buttonGroup2.add(seniorBtn);
        buttonGroup2.add(pwdBtn);
        buttonGroup2.add(naBtn);

        // Set action commands for priority buttons
        pregnantBtn.setActionCommand("Pregnant");
        seniorBtn.setActionCommand("Senior");
        pwdBtn.setActionCommand("PWD");
        naBtn.setActionCommand("N/A");

        // Retrieve selected gender and priority
        String selectedGender = buttonGroup1.getSelection() != null ? buttonGroup1.getSelection().getActionCommand() : "No gender selected";
        String selectedPriority = buttonGroup2.getSelection() != null ? buttonGroup2.getSelection().getActionCommand() : "No priority selected";

        // Display or use the selected values
        System.out.println("Selected Gender: " + selectedGender);
        System.out.println("Selected Priority: " + selectedPriority);
       
            
        try{
           pst = con.prepareStatement("INSERT INTO patientrecords (patientName,patientDOB,patientContact,patientEmergency,patientAddress,patientAllergies,patientGender,patientPriority) VALUES (?,?,?,?,?,?,?,?)");
           
           pst.setString(1, name);
           pst.setString(2, bday);
           pst.setString(3, contact);
           pst.setString(4, emergency);
           pst.setString(5, address);
           pst.setString(6, allergies);
           pst.setString(7, selectedGender);
           pst.setString(8, selectedPriority);
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(null,"Info saved! :)");
     
           
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
        }
       
    }//GEN-LAST:event_nextBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    private void patientBdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientBdayActionPerformed

    private void patientNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNumberActionPerformed

    private void maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnActionPerformed

    private void naBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naBtnActionPerformed

    private void pwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientInformationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JRadioButton naBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField patientAddress;
    private javax.swing.JTextField patientAllergies;
    private javax.swing.JTextField patientBday;
    private javax.swing.JTextField patientEmergencyCon;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField patientNumber;
    private javax.swing.JRadioButton pregnantBtn;
    private javax.swing.JRadioButton pwdBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JRadioButton seniorBtn;
    // End of variables declaration//GEN-END:variables
}
